package br.edu.univas.agencia.model;

// Generated 11/11/2015 21:59:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name = "cidade", catalog = "agencia")
public class Cidade implements java.io.Serializable {

	private Integer id;
	private Estado estado;
	private String nome;
	private Set<PontoTuristico> pontoTuristicos = new HashSet<PontoTuristico>(0);
	private Set<VooReserva> vooReservasForCidadeDestinoId = new HashSet<VooReserva>(
			0);
	private Set<VooReserva> vooReservasForCidadeOrigemId = new HashSet<VooReserva>(
			0);
	private Set<Hotel> hotels = new HashSet<Hotel>(0);
	private Set<Pacote> pacotes = new HashSet<Pacote>(0);
	private Set<Restaurante> restaurantes = new HashSet<Restaurante>(0);

	public Cidade() {
	}

	public Cidade(Estado estado, String nome) {
		this.estado = estado;
		this.nome = nome;
	}

	public Cidade(Estado estado, String nome,
			Set<PontoTuristico> pontoTuristicos,
			Set<VooReserva> vooReservasForCidadeDestinoId,
			Set<VooReserva> vooReservasForCidadeOrigemId, Set<Hotel> hotels,
			Set<Pacote> pacotes, Set<Restaurante> restaurantes) {
		this.estado = estado;
		this.nome = nome;
		this.pontoTuristicos = pontoTuristicos;
		this.vooReservasForCidadeDestinoId = vooReservasForCidadeDestinoId;
		this.vooReservasForCidadeOrigemId = vooReservasForCidadeOrigemId;
		this.hotels = hotels;
		this.pacotes = pacotes;
		this.restaurantes = restaurantes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado_id", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
	public Set<PontoTuristico> getPontoTuristicos() {
		return this.pontoTuristicos;
	}

	public void setPontoTuristicos(Set<PontoTuristico> pontoTuristicos) {
		this.pontoTuristicos = pontoTuristicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidadeByCidadeDestinoId")
	public Set<VooReserva> getVooReservasForCidadeDestinoId() {
		return this.vooReservasForCidadeDestinoId;
	}

	public void setVooReservasForCidadeDestinoId(
			Set<VooReserva> vooReservasForCidadeDestinoId) {
		this.vooReservasForCidadeDestinoId = vooReservasForCidadeDestinoId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidadeByCidadeOrigemId")
	public Set<VooReserva> getVooReservasForCidadeOrigemId() {
		return this.vooReservasForCidadeOrigemId;
	}

	public void setVooReservasForCidadeOrigemId(
			Set<VooReserva> vooReservasForCidadeOrigemId) {
		this.vooReservasForCidadeOrigemId = vooReservasForCidadeOrigemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
	public Set<Hotel> getHotels() {
		return this.hotels;
	}

	public void setHotels(Set<Hotel> hotels) {
		this.hotels = hotels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
	public Set<Pacote> getPacotes() {
		return this.pacotes;
	}

	public void setPacotes(Set<Pacote> pacotes) {
		this.pacotes = pacotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
	public Set<Restaurante> getRestaurantes() {
		return this.restaurantes;
	}

	public void setRestaurantes(Set<Restaurante> restaurantes) {
		this.restaurantes = restaurantes;
	}

}
