package br.edu.univas.agencia.model;

// Generated 30/10/2015 12:29:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Component generated by hbm2java
 */
@Entity
@Table(name = "component")
public class Component implements java.io.Serializable {

	private Integer id;
	private int genericId;
	private String type;
	private Set<PackageComponent> packageComponents = new HashSet<PackageComponent>(
			0);

	public Component() {
	}

	public Component(int genericId, String type) {
		this.genericId = genericId;
		this.type = type;
	}

	public Component(int genericId, String type,
			Set<PackageComponent> packageComponents) {
		this.genericId = genericId;
		this.type = type;
		this.packageComponents = packageComponents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "generic_id", nullable = false)
	public int getGenericId() {
		return this.genericId;
	}

	public void setGenericId(int genericId) {
		this.genericId = genericId;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "component")
	public Set<PackageComponent> getPackageComponents() {
		return this.packageComponents;
	}

	public void setPackageComponents(Set<PackageComponent> packageComponents) {
		this.packageComponents = packageComponents;
	}

}
