package br.edu.univas.agencia.model;

// Generated 11/11/2015 21:59:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "hotel", catalog = "agencia")
public class Hotel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Cidade cidade;
	private String nome;
	private float valor;
	private int numeroVagas;
	private Set<HotelReserva> hotelReservas = new HashSet<HotelReserva>(0);

	public Hotel() {
	}

	public Hotel(Cidade cidade, String nome, float valor, int numeroVagas) {
		this.cidade = cidade;
		this.nome = nome;
		this.valor = valor;
		this.numeroVagas = numeroVagas;
	}

	public Hotel(Cidade cidade, String nome, float valor, int numeroVagas,
			Set<HotelReserva> hotelReservas) {
		this.cidade = cidade;
		this.nome = nome;
		this.valor = valor;
		this.numeroVagas = numeroVagas;
		this.hotelReservas = hotelReservas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cidade_id", nullable = false)
	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "valor", nullable = false, precision = 12, scale = 0)
	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	@Column(name = "numero_vagas", nullable = false)
	public int getNumeroVagas() {
		return this.numeroVagas;
	}

	public void setNumeroVagas(int numeroVagas) {
		this.numeroVagas = numeroVagas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<HotelReserva> getHotelReservas() {
		return this.hotelReservas;
	}

	public void setHotelReservas(Set<HotelReserva> hotelReservas) {
		this.hotelReservas = hotelReservas;
	}

}
