package br.edu.univas.agencia.model;
// Generated 30/10/2015 12:29:48 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PackageComponent generated by hbm2java
 */
@Entity
@Table(name="package_component")
public class PackageComponent  implements java.io.Serializable {


     private Integer id;
     private Component component;
     private Package packageData;

    public PackageComponent() {
    }

    public PackageComponent(Component component, Package packageData) {
       this.component = component;
       this.packageData = packageData;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_component", nullable=false)
    public Component getComponent() {
        return this.component;
    }
    
    public void setComponent(Component component) {
        this.component = component;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_package", nullable=false)
    public Package getPackageData() {
        return this.packageData;
    }
    
    public void setPackageData(Package packageData) {
        this.packageData = packageData;
    }




}


