package br.edu.univas.agencia.model;

// Generated 30/10/2015 12:29:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Package generated by hbm2java
 */
@Entity
@Table(name = "package")
public class Package implements java.io.Serializable {

	private Integer id;
	private Payment payment;
	private String title;
	private String description;
	private float value;
	private int numberOfDay;
	private int quantityOfAdult;
	private int quantityOfChild;
	private Set<PackageComponent> packageComponents = new HashSet<PackageComponent>(
			0);

	public Package() {
	}

	public Package(Payment payment, String title, float value, int numberOfDay,
			int quantityOfAdult, int quantityOfChild) {
		this.payment = payment;
		this.title = title;
		this.value = value;
		this.numberOfDay = numberOfDay;
		this.quantityOfAdult = quantityOfAdult;
		this.quantityOfChild = quantityOfChild;
	}

	public Package(Payment payment, String title, String description,
			float value, int numberOfDay, int quantityOfAdult,
			int quantityOfChild, Set<PackageComponent> packageComponents) {
		this.payment = payment;
		this.title = title;
		this.description = description;
		this.value = value;
		this.numberOfDay = numberOfDay;
		this.quantityOfAdult = quantityOfAdult;
		this.quantityOfChild = quantityOfChild;
		this.packageComponents = packageComponents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_payment", nullable = false)
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@Column(name = "title", nullable = false, length = 75)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "value", nullable = false, precision = 12, scale = 0)
	public float getValue() {
		return this.value;
	}

	public void setValue(float value) {
		this.value = value;
	}

	@Column(name = "number_of_day", nullable = false)
	public int getNumberOfDay() {
		return this.numberOfDay;
	}

	public void setNumberOfDay(int numberOfDay) {
		this.numberOfDay = numberOfDay;
	}

	@Column(name = "quantity_of_adult", nullable = false)
	public int getQuantityOfAdult() {
		return this.quantityOfAdult;
	}

	public void setQuantityOfAdult(int quantityOfAdult) {
		this.quantityOfAdult = quantityOfAdult;
	}

	@Column(name = "quantity_of_child", nullable = false)
	public int getQuantityOfChild() {
		return this.quantityOfChild;
	}

	public void setQuantityOfChild(int quantityOfChild) {
		this.quantityOfChild = quantityOfChild;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packageData")
	public Set<PackageComponent> getPackageComponents() {
		return this.packageComponents;
	}

	public void setPackageComponents(Set<PackageComponent> packageComponents) {
		this.packageComponents = packageComponents;
	}

}
