package br.edu.univas.agencia.model;

// Generated 30/10/2015 12:29:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment")
public class Payment implements java.io.Serializable {

	private Integer id;
	private PaymentWay paymentWay;
	private float value;
	private Set<Package> packages = new HashSet<Package>(0);

	public Payment() {
	}

	public Payment(PaymentWay paymentWay, float value) {
		this.paymentWay = paymentWay;
		this.value = value;
	}

	public Payment(PaymentWay paymentWay, float value, Set<Package> packages) {
		this.paymentWay = paymentWay;
		this.value = value;
		this.packages = packages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_payment_way", nullable = false)
	public PaymentWay getPaymentWay() {
		return this.paymentWay;
	}

	public void setPaymentWay(PaymentWay paymentWay) {
		this.paymentWay = paymentWay;
	}

	@Column(name = "value", nullable = false, precision = 12, scale = 0)
	public float getValue() {
		return this.value;
	}

	public void setValue(float value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payment")
	public Set<Package> getPackages() {
		return this.packages;
	}

	public void setPackages(Set<Package> packages) {
		this.packages = packages;
	}

}
