package br.edu.univas.agencia.model;

// Generated 30/10/2015 12:29:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentWay generated by hbm2java
 */
@Entity
@Table(name = "payment_way")
public class PaymentWay implements java.io.Serializable {

	private Integer id;
	private String description;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public PaymentWay() {
	}

	public PaymentWay(String description) {
		this.description = description;
	}

	public PaymentWay(String description, Set<Payment> payments) {
		this.description = description;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentWay")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
