package br.edu.univas.agencia.model;

// Generated 11/11/2015 21:59:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Voo generated by hbm2java
 */
@Entity
@Table(name = "voo", catalog = "agencia")
public class Voo implements java.io.Serializable {

	private int id;
	private String nomeCompania;
	private Integer quantidadePessoas;
	private Set<VooReserva> vooReservas = new HashSet<VooReserva>(0);

	public Voo() {
	}

	public Voo(int id) {
		this.id = id;
	}

	public Voo(int id, String nomeCompania, Integer quantidadePessoas,
			Set<VooReserva> vooReservas) {
		this.id = id;
		this.nomeCompania = nomeCompania;
		this.quantidadePessoas = quantidadePessoas;
		this.vooReservas = vooReservas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome_compania", length = 45)
	public String getNomeCompania() {
		return this.nomeCompania;
	}

	public void setNomeCompania(String nomeCompania) {
		this.nomeCompania = nomeCompania;
	}

	@Column(name = "quantidade_pessoas")
	public Integer getQuantidadePessoas() {
		return this.quantidadePessoas;
	}

	public void setQuantidadePessoas(Integer quantidadePessoas) {
		this.quantidadePessoas = quantidadePessoas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "voo")
	public Set<VooReserva> getVooReservas() {
		return this.vooReservas;
	}

	public void setVooReservas(Set<VooReserva> vooReservas) {
		this.vooReservas = vooReservas;
	}

}
