package br.edu.univas.agencia.model;

// Generated 11/11/2015 21:59:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VooReserva generated by hbm2java
 */
@Entity
@Table(name = "voo_reserva", catalog = "agencia")
public class VooReserva implements java.io.Serializable {

	private Integer id;
	private Pacote pacote;
	private Voo voo;
	private Cidade cidadeByCidadeDestinoId;
	private Cidade cidadeByCidadeOrigemId;
	private Date dataEmbarque;
	private int tipoVoo;

	public VooReserva() {
	}

	public VooReserva(Pacote pacote, Voo voo, Cidade cidadeByCidadeDestinoId,
			Cidade cidadeByCidadeOrigemId, Date dataEmbarque, int tipoVoo) {
		this.pacote = pacote;
		this.voo = voo;
		this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
		this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
		this.dataEmbarque = dataEmbarque;
		this.tipoVoo = tipoVoo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pacote_id", nullable = false)
	public Pacote getPacote() {
		return this.pacote;
	}

	public void setPacote(Pacote pacote) {
		this.pacote = pacote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "voo_id", nullable = false)
	public Voo getVoo() {
		return this.voo;
	}

	public void setVoo(Voo voo) {
		this.voo = voo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cidade_destino_id", nullable = false)
	public Cidade getCidadeByCidadeDestinoId() {
		return this.cidadeByCidadeDestinoId;
	}

	public void setCidadeByCidadeDestinoId(Cidade cidadeByCidadeDestinoId) {
		this.cidadeByCidadeDestinoId = cidadeByCidadeDestinoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cidade_origem_id", nullable = false)
	public Cidade getCidadeByCidadeOrigemId() {
		return this.cidadeByCidadeOrigemId;
	}

	public void setCidadeByCidadeOrigemId(Cidade cidadeByCidadeOrigemId) {
		this.cidadeByCidadeOrigemId = cidadeByCidadeOrigemId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_embarque", nullable = false, length = 10)
	public Date getDataEmbarque() {
		return this.dataEmbarque;
	}

	public void setDataEmbarque(Date dataEmbarque) {
		this.dataEmbarque = dataEmbarque;
	}

	@Column(name = "tipo_voo", nullable = false)
	public int getTipoVoo() {
		return this.tipoVoo;
	}

	public void setTipoVoo(int tipoVoo) {
		this.tipoVoo = tipoVoo;
	}

}
